services:
  updater:
    container_name: updater
    image: wovnep/tauri-update-server:0.2.1
    ports:
      - "3000:8080"
    environment:
      - USERNAME=wovnep
      - REPO=tauri-updater
      - API_KEY=${API_KEY}
      - DEFAULT_LANG=en-US
      - SIGNATURE=true
      - TAG_STRUCTURE=v