name: docker-readme

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/docker-readme.yml
  workflow_dispatch:

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - name: Copy the repository
        uses: actions/checkout@v3
 
      - name: Docker Hub README update
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: wovnep/tauri-update-server
          short-description: ${{ github.event.repository.description }}